os: osx
osx_image: xcode10
language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn package

before_deploy:
  - git config --local user.name "$(npx -c 'echo "$npm_package_author_name"')"
  - git config --local user.email "$(npx -c 'echo "$npm_package_author_email"')"
  - git tag "v$(npx -c 'echo "$npm_package_version"')"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true

branches:
  only:
    - master
